name: ROH-Cayo
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy>=1.2
  - pandas>=1.2
  - matplotlib>=3.1
  - ipykernel>=6.0
  - pip
  - pip:
    - git+https://github.com/flopau76/IBDecay@v0.1-alpha

